Add cross compile to aarch64, armhf, and armel
nestybox/sysbox-fs pull request #51
Opened 2021-07-20 21:23 UTC by abalmos

Needed for nestybox/sysbox#360

2021-07-20 21:28 UTC, abalmos commented
Force push was due to missing signoffs

2021-07-21 04:48 UTC, rodnymolina requested changes
LG. Just have a couple of minor suggestions.

2021-07-21 20:23 UTC, abalmos commented on Makefile
> +sysbox-fs: $(SYSFS_BUILDDIR)/$(SYSFS_TARGET)
Fixed the lint

2021-07-21 20:23 UTC, abalmos commented on Makefile
> +sysbox-fs-debug: $(SYSFS_BUILDDIR)/$(SYSFS_DEBUG_ TARGET)
Good catch, thanks!

2021-07-21 20:25 UTC, rodnymolina approved these changes
LG

2021-07-21 20:26 UTC, rodnymolina commented
@abalmos, please check [this](https://github.com/nestybox/sysbox-fs/pull/51/checks?check_run_id=3127967936) out to meet the DCO requirement.

2021-07-21 20:34 UTC, merged